### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mkowales**

### CODE REVIEW

**Review by mkowales — COMMENTED** [review]
go 4 it

**Comment by a-a-ron** [comment]
Hey, @mkowales. I though it may be easier to respond back right in your PR 😄 

You weren't able to see the `add-images-links` branch in the dropdown because you prematurely merged the pull request. This is also the reason why you couldn't see the pencil icons you mentioned. Since you merged the pull request, you can't edit files in that same pull request again. 

So, now what we're working off script a bit, let's see if we can get this to work without having to start over 😉  In this pull request,  edit the `_includes/02-image.md` file so that it is now referencing the image you just added. It should look like this `my avatar image`. Commit that change to this pull request and then edit the pull request description to say something other than the default "No description provided". 

Send me an @a-a-ron in a comment when finished and i'll approve this pull request so you can merge it in.

**Review by mkowales — COMMENTED** [review]
I've tried to follow your instructions @a-a-ron

**Comment by a-a-ron** [comment]
Hi @mkowales, I don't see a commit made to this pull request. What you'll need to do is edit the `_includes/02-image.md` with your new image link in this same pull request. You can do by following the below steps:

- Navigate to the **Code** tab at the top
- Under the branch dropdown button, select the `mkowales-patch-2` branch name
- Open up the `_includes/02-image.md` file and replace the default text on **line 1** with `my avatar image`
- Commit that change and then let me know

**Pull request merged**
